### ISSUE TITLE
Question about font

### ISSUE THREAD

**Issue by pfitzseb** [simurai/duotone-dark-syntax#16]
Hiya,
just a short question about the font you show in the readme: Is this some older version of Fira or something? I really like it, but Fira Mono looks different for me (note the serif on the `r` for example, which is lacking in your screenshot):
![fira](https://cloud.githubusercontent.com/assets/6735977/13505731/cff03ca6-e17a-11e5-86dd-e2d926d6962f.PNG)
If it indeed is an old version, do you know where I could find that?

Thanks!

**Comment by simurai** [comment]
Ha.. interesting. Yeah, it's Fira Mono. Not sure if it's old, but I think I got it from https://github.com/mozilla/Fira.

**Comment by simurai** [comment]
Maybe it's the older `4.106` version: https://github.com/mozilla/Fira/releases/tag/4.106

**Comment by pfitzseb** [comment]
I don't think so -- the Mono variant didn't change since that release. Still, thanks for looking into it.

**Comment by simurai** [comment]
Strange yeah.. anyways.. I put it up on dropbox: https://dl.dropboxusercontent.com/u/2187527/FiraMono.zip

**Comment by varemenos** [comment]
what OS and what versions do you guys use?
The fonts are most likely different due to font renderer of your OS.

Allow me to assume that @simurai uses OSX and @pfitzseb uses Windows or a Linux distro?

**Comment by pfitzseb** [comment]
Yeah, I'm on Windows. I'll try the font uploaded by @simurai (thanks!) and report back. 

It'd be really strange if those differences were due to the OS's renderer though -- a completely missing serif is a pretty significant change!

**Comment by varemenos** [comment]
Yes it is a significant change but I don't think you can do much about it.
You should see what's the state like in some Linux distros.

**Comment by pfitzseb** [comment]
Your version is indeed older, @simurai, it's 3.111 vs the newest 3.206. And it looks much better:
![fira](https://cloud.githubusercontent.com/assets/6735977/13547112/7b536024-e2c4-11e5-9c17-a6a073242966.PNG)
Thanks for the help!

**Comment by simurai** [comment]
:+1:  I kinda like `3.111` better too.
