### ISSUE TITLE
About update?

### ISSUE THREAD

**Issue by lednhatkhanh** [simurai/duotone-dark-syntax#22]
Hey, is it true that if there are any updates on this project: https://github.com/simurai/duotone-syntax
This theme will be updated too?

**Comment by simurai** [comment]
Yes, all updates.. except for the colors.

Although, I started with `2.0`. So it might take a bit longer till that will be ready.

**Comment by simurai** [comment]
Actually, now that there is https://github.com/simurai/tone-syntax/, this theme is deprecated. Might not be 100% the same, but lets you customize more.
