### ISSUE TITLE
Command palette has weird aligned scrollbars

### ISSUE THREAD

**Issue by jdsimcoe** [simurai/duotone-dark-syntax#3]
![duotone-dark-scrollbar-bug](https://cloud.githubusercontent.com/assets/275617/7764986/4d9e82e8-000d-11e5-8aaa-2a69297d01eb.png)

@simurai I've noticed this on other themes. If this is a core issues what repo would I submit the bug to?

**Comment by simurai** [comment]
That's odd.. maybe in the [fuzzy-finder](https://github.com/atom/fuzzy-finder/issues/new) repo?

**Comment by jdsimcoe** [comment]
Weird this issue has appeared to go away.

**Comment by simurai** [comment]
Haa.. well, it comes back feel free to make a new issue.
