### ISSUE TITLE
little issue with colors for invisibles - imo

### ISSUE THREAD

**Issue by ghost** [simurai/duotone-dark-syntax#5]
Just found and installed Duotone. Perfect colors. But when in Atom the option 'Show invisibles' is enabled, then I think colors for invisible chars are too similar to colors like for braces, colons, etc.

Here a JS screenshot
![image](https://cloud.githubusercontent.com/assets/623932/9927746/5cdbc9d4-5d21-11e5-8e5d-62bccaebd5a2.png)

Here a JSON screenshot
![image](https://cloud.githubusercontent.com/assets/623932/9927950/c22456b6-5d22-11e5-8fff-98d1dbc53430.png)

**Comment by simurai** [comment]
Yeah, they clash a bit and it looks pretty cluttered.

If you wanna keep invisibles, tyu could change the color in your `styles.less` to something stronger. Here an example with dark red:

``` less
atom-text-editor::shadow .invisible-character {
  color: hsl(0,44%,44%);
}
```

**Comment by fibric** [comment]
that looks much better now, thx :)

![screen shot 2015-09-15 at 21 32 15](https://cloud.githubusercontent.com/assets/623932/9976913/f3cc6e24-5ef3-11e5-831b-8c481a96073f.png)

**Comment by ghost** [comment]
changed my personal styles to:

```
atom-text-editor::shadow .invisible-character {
   color: hsl(0,25%,25%);
}
```
