### ISSUE TITLE
Jade support

### ISSUE THREAD

**Issue by AgtLucas** [simurai/duotone-dark-syntax#6]
Hello!

There's any ETA or interest for Jade support?

I've forked the repo and tried to make Jade support on my own, but not joy. :laughing: 

Thanks! :)

**Comment by simurai** [comment]
Which Jade language package are you using? This one https://atom.io/packages/language-jade?

Here the example from http://jade-lang.com

![screen shot 2015-10-23 at 9 24 03 pm](https://cloud.githubusercontent.com/assets/378023/10692446/9a396f62-79cc-11e5-8da1-57edeaae16e3.png)

Not bad, but yeah.. could be more in sync with `HTML`. I'm still not sure which languages to support. Any or just the ones that get bundled in Atom.

**Comment by AgtLucas** [comment]
Yep, I'm using the same package.

I'll try to improve it. :)

**Comment by simurai** [comment]
I'm still not sure which language should be included, see https://github.com/simurai/duotone-syntax/issues/2. But until then, it might not hurt to have Jade too.

How about something like:

![screen shot 2016-01-04 at 7 24 40 pm](https://cloud.githubusercontent.com/assets/378023/12087861/c1f8073a-b319-11e5-87e9-494df262bbbb.png)

It should mimic how HTML is highlighted.

**Comment by AgtLucas** [comment]
@simurai LGTM. 

Thanks! :)
