### ISSUE TITLE
C# Support

### ISSUE THREAD

**Issue by cmilr** [simurai/duotone-dark-syntax#7]
Love this theme. Would really like to be able to use it with C#. Any chance?

**Comment by simurai** [comment]
Sure. We could try to use the same as `c` and see if that already improves highlighting.

Or if you have a better code example than just this [hello world](https://github.com/atom/language-examples/blob/master/languages/csharp.cs) and maybe a few tests.. that would be great.

**Comment by cmilr** [comment]
Great, I'd be happy to help. Here's a skeleton of a C# program: https://gist.github.com/jguarShark/6e89f0437f6b37057771

And here are a couple of scripts I've written in C#.
https://gist.github.com/jguarShark/dd22583c09a9f54df913
https://gist.github.com/jguarShark/4eba0fba53e0bd13fa2d

I'm not really sure what a test would consist of?

**Comment by simurai** [comment]
Thanks for the sample code. Made a PR #9 that improves highlighting a bit. A problem is that the `language-cs` package doesn't tokenize that much. So there is no way to select certain parts of the code.
